### ISSUE TITLE
Suggestion: models' size info

### ISSUE THREAD

**Issue by syvasha** [PatPL/Generic-Engines-Web#25]
Hi!

First of all, I really appreciate your work! Thank you.

The suggestion is: would it be possible to make the model selection screen also show model sizes?
Something like "RD-100 (L 3m D 1.25 m)"
It would be useful, I think.

Thanks!

**Comment by PatPL** [comment]
The actual, original sizes (Ingame, from mods) don't really matter, as the engines will be resized to a set absolute size, regardless of the chosen model.
If you'd like to see the model aspect ratio (Length/Diameter) instead, I guess it's possible, but I don't see the point, as you can easily match the length to the given model/diameter in 'Size' tab.

I really don't see the reason. Give me a possible use-case and I will reconsider it.
Also, due to uni work and exams the soonest I will be able to resume working on this project is in more or less a month

**Comment by syvasha** [comment]
I realized I missed a lot of the config options, haven't noticed the slider on the bottom.
Since nobody else complained, it must have been just me sleepy.

I appreciate the quick reply, have exams coming up myself.

I would be glad to perhaps add somewhat to the wiki, for a more comprehensive "manual". Since nobody else seems to be complaining, it is nothing critical, though.

**Comment by syvasha** [comment]
I wrote up a brief overview of the editor's fields, to be put in "creating your first engine":


_Between this line:_ 
Double click a field to open edit mode. 

The configurable properties are:
  - _ID:_ KSP's internal identification for the part config
  - _Name_ Displayed name of the engine, Manufacturer and description.
  - _Polymorphism:_ multi-config/multimodal settings, see [Multimode engine config](https://github.com/PatPL/Generic-Engines-Web/wiki/Multimode-engine-config) and [Multiconfig engine config](https://github.com/PatPL/Generic-Engines-Web/wiki/Multiconfig-engine-config)
  - _Type:_ whether it is a liquid or solid fuel engine (see [the SRB guide](https://github.com/PatPL/Generic-Engines-Web/wiki/SRB-guide))
  - _Propulsion:_ configure thrust, ISP and fuel flow rate
  - _Minimum thrust:_ configure throttle range
  - _Pressure-fed, ullage:_ set whether the engine is to require pressurized propellant (or no, in case it has a turbopump) and suffers from ullage
  - _Propellants:_ configure the fuels and their (mass or volume) mixing ratios 
  - _Visuals, Size:_ choose the engine model, dimensions, and exhaust plume color. See:
    - [(Base | Bell) engine width](https://github.com/PatPL/Generic-Engines-Web/wiki/(Base-%7C-Bell)-engine-width) for sizing
    - [Exhaust effect config](https://github.com/PatPL/Generic-Engines-Web/wiki/Exhaust-effect-config) for exhaust configuration
  - _TestFlight:_ reliability configuration, see [Test Flight config](https://github.com/PatPL/Generic-Engines-Web/wiki/Test-Flight-config)
  - _R&D Unlock node:_ the tech tree node the engine (config) is researched in
  - _Entry cost, cost:_ part unlock costs and the actual part costs as seen in the VAB
  - _Alternator:_ whether the engine produces electricity; 1 kW = 1 EC/s
  - _Tank:_ whether the engine has an integrated tank, see [Internal tank config](https://github.com/PatPL/Generic-Engines-Web/wiki/Internal-tank-config)
  - _Thrust curve:_ change the behavior of thrust and ISP with altitude, or leave untouched for a generalized performance curve 
  
_And the rest of the paragraph_:
Commit your change by clicking Enter, ok clicking off the field. Press Escape to discard the changes. This applies to the list name as well. Don't forget to mark the engine as 'Active' (First checkbox field). **Inactive engines will not be exported**. (They will still be saved to the engine list).

**Comment by PatPL** [comment]
This is a good idea, thanks for taking your time to write this. It looks fine, I'll tweak it a bit and add it right away. Good luck with your exams. Thank you.
